from chainer0.functions.relu import relu
from chainer0.functions.relu import ReLU
from chainer0.functions.trigonometric import Sin
from chainer0.functions.trigonometric import sin
from chainer0.functions.trigonometric import Cos
from chainer0.functions.trigonometric import cos
from chainer0.functions.exponential import Log
from chainer0.functions.exponential import log
from chainer0.functions.exponential import Exp
from chainer0.functions.exponential import exp
from chainer0.functions.sqrt import Sqrt
from chainer0.functions.sqrt import sqrt
from chainer0.functions.sigmoid import Sigmoid
from chainer0.functions.sigmoid import sigmoid
from chainer0.functions.tanh import tanh
from chainer0.functions.tanh import Tanh
from chainer0.functions.transpose import Transpose
from chainer0.functions.transpose import transpose
from chainer0.functions.linear import Linear
from chainer0.functions.linear import linear
from chainer0.functions.matmul import MatMul
from chainer0.functions.matmul import matmul
from chainer0.functions.sum import Sum
from chainer0.functions.sum import sum
from chainer0.functions.sum import SumTo
from chainer0.functions.sum import sum_to
from chainer0.functions.broadcast import BroadcastTo
from chainer0.functions.broadcast import broadcast_to
from chainer0.functions.reshape import Reshape
from chainer0.functions.reshape import reshape
from chainer0.functions.flatten import Flatten
from chainer0.functions.flatten import flatten
from chainer0.functions.array import GetItem
from chainer0.functions.array import get_item
from chainer0.functions.embed_id import EmbedId
from chainer0.functions.embed_id import embed_id
from chainer0.functions.mean_squared_error import MeanSquaredError
from chainer0.functions.mean_squared_error import mean_squared_error
from chainer0.functions.softmax_cross_entropy import SoftmaxCrossEntropy
from chainer0.functions.softmax_cross_entropy import softmax_cross_entropy
from chainer0.functions.accuracy import Accuracy
from chainer0.functions.accuracy import accuracy